services:
  deoxys_xarm:
    build:
      context: ..
      dockerfile: deoxys_control/Dockerfile
    image: deoxys_xarm
    container_name: deoxys_xarm_cont
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../deoxys_control:/home/hw_ctrl_ws/src/deoxys_control
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=55
      - DISPLAY=${DISPLAY}
  deoxys_franka:
    build:
      context: ..
      dockerfile: deoxys_control/Dockerfile_franka
    image: deoxys_franka
    container_name: deoxys_franka_cont
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
        #- ../deoxys_control:/home/hw_ctrl_ws/src/deoxys_control
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=55
      - DISPLAY=${DISPLAY}
