services:
  deoxys_xarm_gpu:
    build:
      context: ..
      dockerfile: deoxys_control/Dockerfile
      args:
        - TARGET_ENV=gpu
    image: deoxys_xarm_gpu
    container_name: deoxys_xarm_cont
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../deoxys_control:/home/hw_ctrl_ws/src/deoxys_control
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=55
      - DISPLAY=${DISPLAY}
    ports:
      - 5555:5555
      - 5556:5556

  deoxys_xarm:
    build:
      context: ..
      dockerfile: deoxys_control/Dockerfile
      args:
        - TARGET_ENV=cpu
    image: deoxys_xarm
    container_name: deoxys_xarm_cont
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../deoxys_control:/home/hw_ctrl_ws/src/deoxys_control
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=55
      - DISPLAY=${DISPLAY}

  deoxys_franka:
    build:
      context: ..
      dockerfile: deoxys_control/Dockerfile_franka
    image: deoxys_franka
    container_name: deoxys_franka_cont
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
        #- ../deoxys_control:/home/hw_ctrl_ws/src/deoxys_control
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    restart: unless-stopped
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=55
      - DISPLAY=${DISPLAY}

