FROM nvidia/cuda:12.5.0-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    curl gnupg2 lsb-release software-properties-common build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --no-install-recommends -y \
    libusb-1.0-0-dev \
    libudev-dev \
    libgtk-3-dev \
    libglfw3-dev \
    python3-pip \
    git \
    xauth \
    vim \
    wget && apt-get clean

RUN mkdir -p /home/hw_ctrl_ws/src

WORKDIR /home/hw_ctrl_ws/src
COPY deoxys_control ./deoxys_control
WORKDIR /home/hw_ctrl_ws/src/deoxys_control/deoxys
RUN cd /home/hw_ctrl_ws/src/deoxys_control/deoxys && ./InstallPackage
RUN cd /home/hw_ctrl_ws/src/deoxys_control/deoxys && make -j build_franka=1
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hw_ctrl_ws/src/deoxys_control/deoxys" >> /root/.bashrc
RUN pip3 install zmq pyquaternion numpy pyRobotiqGripper
WORKDIR /home/hw_ctrl_ws/src
CMD ["bash"]
