LOCAL_HOST:
  NAME: "droid"
  IP_ETH: 172.16.0.2
  IP_WIFI: 192.168.50.178

CTRL_HOST:
  NAME: "droid"
  IP_ETH: 172.16.0.3
  ARM_PUB_PORT: 5556
  ARM_SUB_PORT: 5555
  GRIPPER_PUB_PORT: 5558
  GRIPPER_SUB_PORT: 5557
  HAND_PORT: 6669

ROBOT:
  IP: 172.16.0.1

TELEOP:
  VR_HOST: "192.168.50.89"
  DEPTH_CMD_PORT: 12321
  IK_RESULT_PORT: 12345
  POSE_CMD_PORT: 12346
  ROKOKO_PORT: 14043
  HAND_INFO_PORT: 65432

CONTROL:
  STATE_PUBLISHER_RATE: 100
  POLICY_RATE: 20
  TRAJ_RATE: 500
  ZMQ_NOBLOCK: true

ARM_LOGGER:
  CONSOLE:
    LOGGER_NAME: "arm_logger"
    LEVEL: "info"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_arm_program.log"
    LEVEL: "debug"
    USE: true

GRIPPER_LOGGER:
  CONSOLE:
    LOGGER_NAME: "gripper_logger"
    LEVEL: "info"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_gripper_program.log"
    LEVEL: "debug"
    USE: true
